# version: "3.8"
services:
  product-service:
    build:
      context: ./product-service
    image : product-service
    ports:
      - "3000:8000"
  user-service:
    build:
      context: ./user-service
    image: user-service
    ports:
      - "3001:8000"
